// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TrackAPI {
  final int? id;
  final String? title;
  final List<String>? artistId;
  final String? albumId;
  final int? trackNumber;
  final int? discNumber;
  final int durationMs;
  final String? pictureId;
  final String location;
  final String mountPoint;
  final DateTime createdAt;

  const TrackAPI({
    this.id,
    this.title,
    this.artistId,
    this.albumId,
    this.trackNumber,
    this.discNumber,
    required this.durationMs,
    this.pictureId,
    required this.location,
    required this.mountPoint,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artistId.hashCode ^
      albumId.hashCode ^
      trackNumber.hashCode ^
      discNumber.hashCode ^
      durationMs.hashCode ^
      pictureId.hashCode ^
      location.hashCode ^
      mountPoint.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackAPI &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artistId == other.artistId &&
          albumId == other.albumId &&
          trackNumber == other.trackNumber &&
          discNumber == other.discNumber &&
          durationMs == other.durationMs &&
          pictureId == other.pictureId &&
          location == other.location &&
          mountPoint == other.mountPoint &&
          createdAt == other.createdAt;
}
