// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Track {
  final int id;
  final String? pictureId;
  final String? title;
  final String? artist;
  final String? album;
  final int durationMs;
  final String file;
  final String directory;
  final String mountPoint;
  final DateTime createdAt;

  const Track({
    required this.id,
    this.pictureId,
    this.title,
    this.artist,
    this.album,
    required this.durationMs,
    required this.file,
    required this.directory,
    required this.mountPoint,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pictureId.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationMs.hashCode ^
      file.hashCode ^
      directory.hashCode ^
      mountPoint.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pictureId == other.pictureId &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationMs == other.durationMs &&
          file == other.file &&
          directory == other.directory &&
          mountPoint == other.mountPoint &&
          createdAt == other.createdAt;
}
