// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Model {
  final int id;
  final String? title;
  final int? albumId;
  final int? artistId;
  final int duration;
  final String filePath;
  final String? pictureId;
  final String mountPoint;
  final String? createdAt;

  const Model({
    required this.id,
    this.title,
    this.albumId,
    this.artistId,
    required this.duration,
    required this.filePath,
    this.pictureId,
    required this.mountPoint,
    this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      albumId.hashCode ^
      artistId.hashCode ^
      duration.hashCode ^
      filePath.hashCode ^
      pictureId.hashCode ^
      mountPoint.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Model &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          albumId == other.albumId &&
          artistId == other.artistId &&
          duration == other.duration &&
          filePath == other.filePath &&
          pictureId == other.pictureId &&
          mountPoint == other.mountPoint &&
          createdAt == other.createdAt;
}
