// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple.dart';

bool trackQueryFilterCondition(
        {required String query, required TrackDTO track, dynamic hint}) =>
    RustLib.instance.api
        .trackQueryFilterCondition(query: query, track: track, hint: hint);

String durationToString({required Duration duration, dynamic hint}) =>
    RustLib.instance.api.durationToString(duration: duration, hint: hint);
