name: just_audio_media_kit
description: package:media_kit bindings for just_audio
version: 2.0.2
repository: https://github.com/Pato05/just_audio_media_kit

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  just_audio_platform_interface: ^4.2.2
  media_kit:
    git:
      url: https://github.com/lazykern/media-kit.git
      ref: 64be0a0dfad06dff613207d5c83f91e55613343f
      path: media_kit

  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
